#!/usr/bin/env perl
use strict;
use warnings;

my $size = 1000; # in megabyes
my $size_arg = $size * 2048;
my $type = q{Case-sensitive Journaled HFS+};
my $name = sprintf "ramdisk-%s-%06u", $^T, $$;
my $dev  = `hdiutil attach -nomount ram://$size_arg`;

chomp $dev;
$dev =~ s/\s+\z//;

print "creating /Volumes/$name on $dev\n";

exec { 'diskutil' } qw(diskutil eraseVolume), $type, $name, $dev;
